package casino.cashier;


import casino.idfactory.BetID;
import casino.idfactory.CardID;
import casino.idfactory.IDFactory;
import sun.rmi.runtime.Log;

import java.util.*;

public class GamblerCard implements IGamblerCard {
    private Set<BetID> betIDSInCard;
    private CardID cardID;

    public GamblerCard(){
        this.betIDSInCard = new HashSet<>();
        cardID = (CardID ) IDFactory.generateID("CARDID");
    }

    //helping property for returnBetIDs_shouldReturnAllBetIdsGeneratedByTheCard
    public Set<BetID> getBetIDSInCard() {
        return this.betIDSInCard;
    }

    /**
     * Returns all generated betID's by this card
     * @should return all bet Ids generated by the card
     * @return
     */
    @Override
    public Set<BetID> returnBetIDs() {
        return this.betIDSInCard;
    }

    /**
     * Returns all generated betID's by this card, and clears all betID's from the card.
     * @should clear all generated Ids by the card after returning them
     * @return
     */
    @Override
    public Set<BetID> returnBetIDsAndClearCard() {
        Set<BetID> tempSet = new HashSet<>();
        tempSet.addAll(this.betIDSInCard);

        if(!this.betIDSInCard.isEmpty()){
            this.betIDSInCard.clear();
        }

        return tempSet;
    }

    /**
     * The card generates a unique betID for every bet made by the gambler on the machine
     * The generated betId is added to the list of betIds
     * @should generate a betID and add it to the list of betIds
     * @return
     */
    @Override
    public BetID generateNewBetID() {
        BetID newBetId = (BetID) IDFactory.generateID("BETID");
        if(newBetId != null) this.betIDSInCard.add(newBetId);
        return newBetId;
    }

    /**
     * 1) Return number of betID's generated on this card.
     * @should return an int indicating the number of Ids stored on the card
     * @return
     */
    @Override
    public int getNumberOfBetIDs() {
        return this.betIDSInCard.size();
    }

    /**
     * Return ID of the card
     * @should return the Id of the card
     * @return
     */
    @Override
    public CardID getCardID() {
        return this.cardID;
    }
}
